/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gizmo_gsdk_logo_LibLogoRecog */

#ifndef _Included_com_gizmo_gsdk_logo_LibLogoRecog
#define _Included_com_gizmo_gsdk_logo_LibLogoRecog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gizmo_gsdk_logo_LibLogoRecog
 * Method:    loadLogos
 * Signature: ([CZ)I
 */
JNIEXPORT jint JNICALL Java_com_gizmo_gsdk_logo_LibLogoRecog_loadLogos
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     com_gizmo_gsdk_logo_LibLogoRecog
 * Method:    recognize
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_gizmo_gsdk_logo_LibLogoRecog_recognize
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_gizmo_gsdk_logo_LibLogoRecog
 * Method:    init
 * Signature: (ZFIIIF)V
 */
JNIEXPORT void JNICALL Java_com_gizmo_gsdk_logo_LibLogoRecog_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
