/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gizmo_gsdk_opencv_OpenCVTest */

#ifndef _Included_com_gizmo_gsdk_opencv_OpenCVTest
#define _Included_com_gizmo_gsdk_opencv_OpenCVTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gizmo_gsdk_opencv_OpenCVTest
 * Method:    gray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_gizmo_gsdk_opencv_OpenCVTest_gray
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
